1. Importing libraries

In [3]:
import pandas as pd
import numpy as np
import os 
import pickle

2. Importing datasets

In [6]:
path = r'C:/Users/C SaiVishwanath/Documents/CF/Data Immersion/Achievement 6'

In [64]:
df_pop20 = pd.read_csv(os.path.join(path, '02_Data', 'Original', 'US Population 2010-2020.csv'), sep=';', index_col = False, encoding='latin1')
df_pop24 = pd.read_csv(os.path.join(path, '02_Data', 'Original', 'US Population 2020-2024.csv'), sep=';', index_col = False, encoding='latin1')

In [66]:
df_pop20

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020
0,40,3,6,1,0,Alabama,Alabama,4779736,4780118,4785514,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4921532
1,50,3,6,1,1,Alabama,Autauga County,54571,54582,54761,55229,54970,54747,54922,54903,55302,55448,55533,55769,56145
2,50,3,6,1,3,Alabama,Baldwin County,182265,182263,183121,186579,190203,194978,199306,203101,207787,212737,218071,223565,229287
3,50,3,6,1,5,Alabama,Barbour County,27457,27454,27325,27344,27172,26946,26768,26300,25828,25169,24887,24657,24589
4,50,3,6,1,7,Alabama,Bibb County,22915,22904,22858,22736,22657,22510,22541,22553,22590,22532,22300,22313,22136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43580,44000,45032,45189,44996,44780,44319,43663,43188,42917,42673
3190,50,4,8,56,39,Wyoming,Teton County,21294,21298,21298,21422,21643,22335,22801,23083,23255,23383,23261,23385,23497
3191,50,4,8,56,41,Wyoming,Uinta County,21118,21121,21090,20901,21008,20969,20835,20777,20711,20449,20299,20196,20215
3192,50,4,8,56,43,Wyoming,Washakie County,8533,8528,8531,8451,8410,8417,8277,8282,8180,8013,7886,7824,7760
3193,50,4,8,56,45,Wyoming,Weston County,7208,7208,7198,7142,7075,7132,7134,7202,7228,6962,6895,6880,6743

In [68]:
df_pop24

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
0,40,3,6,1,0,Alabama,Alabama,5025369,5033094,5049196,5076181,5117673,5157699
1,50,3,6,1,1,Alabama,Autauga County,58800,58909,59191,59736,60436,61464
2,50,3,6,1,3,Alabama,Baldwin County,231767,233244,239411,246577,254107,261608
3,50,3,6,1,5,Alabama,Barbour County,25226,24975,24517,24722,24644,24358
4,50,3,6,1,7,Alabama,Bibb County,22284,22176,22344,21983,21890,22258
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,50,4,8,56,37,Wyoming,Sweetwater County,42270,42196,41630,41322,41288,41273
3191,50,4,8,56,39,Wyoming,Teton County,23327,23384,23613,23341,23368,23272
3192,50,4,8,56,41,Wyoming,Uinta County,20448,20461,20690,20722,20724,20621
3193,50,4,8,56,43,Wyoming,Washakie County,7685,7663,7727,7728,7736,7662
3194,50,4,8,56,45,Wyoming,Weston County,6838,6817,6747,6872,6828,6866

3. Dropping and renaming columns on pop20

In [82]:
#Dropping in pop20
df_pop20_wrangled = pop20.drop(columns=['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 
                        'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010', 
                        'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2020'
                ])

In [86]:
df_pop20_wrangled

,STNAME,CTYNAME,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,Alabama,Alabama,4854803,4866824,4877989,4891628,4907965
1,Alabama,Autauga County,54903,55302,55448,55533,55769
2,Alabama,Baldwin County,203101,207787,212737,218071,223565
3,Alabama,Barbour County,26300,25828,25169,24887,24657
4,Alabama,Bibb County,22553,22590,22532,22300,22313
...,...,...,...,...,...,...,...
3189,Wyoming,Sweetwater County,44780,44319,43663,43188,42917
3190,Wyoming,Teton County,23083,23255,23383,23261,23385
3191,Wyoming,Uinta County,20777,20711,20449,20299,20196
3192,Wyoming,Washakie County,8282,8180,8013,7886,7824
3193,Wyoming,Weston County,7202,7228,6962,6895,6880

In [96]:
#Renaming in pop20_wrangled
df_pop20_wrangled2 = df_pop20_wrangled.rename(columns = {
    'STNAME': 'State',
    'CTYNAME': 'County',
    'POPESTIMATE2015': 'Pop2015',
    'POPESTIMATE2016': 'Pop2016',
    'POPESTIMATE2017': 'Pop2017',
    'POPESTIMATE2018': 'Pop2018',
    'POPESTIMATE2019': 'Pop2019',
})

In [98]:
df_pop20_wrangled2

        State             County  Pop2015  Pop2016  Pop2017  Pop2018  Pop2019
0     Alabama            Alabama  4854803  4866824  4877989  4891628  4907965
1     Alabama     Autauga County    54903    55302    55448    55533    55769
2     Alabama     Baldwin County   203101   207787   212737   218071   223565
3     Alabama     Barbour County    26300    25828    25169    24887    24657
4     Alabama        Bibb County    22553    22590    22532    22300    22313
...       ...                ...      ...      ...      ...      ...      ...
3189  Wyoming  Sweetwater County    44780    44319    43663    43188    42917
3190  Wyoming       Teton County    23083    23255    23383    23261    23385
3191  Wyoming       Uinta County    20777    20711    20449    20299    20196
3192  Wyoming    Washakie County     8282     8180     8013     7886     7824
3193  Wyoming      Weston County     7202     7228     6962     6895     6880

[3194 rows x 7 columns]

4. Dropping and renaming columns on pop24

In [104]:
df_pop24

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
0,40,3,6,1,0,Alabama,Alabama,5025369,5033094,5049196,5076181,5117673,5157699
1,50,3,6,1,1,Alabama,Autauga County,58800,58909,59191,59736,60436,61464
2,50,3,6,1,3,Alabama,Baldwin County,231767,233244,239411,246577,254107,261608
3,50,3,6,1,5,Alabama,Barbour County,25226,24975,24517,24722,24644,24358
4,50,3,6,1,7,Alabama,Bibb County,22284,22176,22344,21983,21890,22258
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,50,4,8,56,37,Wyoming,Sweetwater County,42270,42196,41630,41322,41288,41273
3191,50,4,8,56,39,Wyoming,Teton County,23327,23384,23613,23341,23368,23272
3192,50,4,8,56,41,Wyoming,Uinta County,20448,20461,20690,20722,20724,20621
3193,50,4,8,56,43,Wyoming,Washakie County,7685,7663,7727,7728,7736,7662
3194,50,4,8,56,45,Wyoming,Weston County,6838,6817,6747,6872,6828,6866

In [106]:
#Dropping in pop24
df_pop24_wrangled = pop24.drop(columns=['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 
                        'ESTIMATESBASE2020'
                ])

In [108]:
df_pop24_wrangled

,STNAME,CTYNAME,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
0,Alabama,Alabama,5033094,5049196,5076181,5117673,5157699
1,Alabama,Autauga County,58909,59191,59736,60436,61464
2,Alabama,Baldwin County,233244,239411,246577,254107,261608
3,Alabama,Barbour County,24975,24517,24722,24644,24358
4,Alabama,Bibb County,22176,22344,21983,21890,22258
...,...,...,...,...,...,...,...
3190,Wyoming,Sweetwater County,42196,41630,41322,41288,41273
3191,Wyoming,Teton County,23384,23613,23341,23368,23272
3192,Wyoming,Uinta County,20461,20690,20722,20724,20621
3193,Wyoming,Washakie County,7663,7727,7728,7736,7662
3194,Wyoming,Weston County,6817,6747,6872,6828,6866

In [110]:
#Renaming in pop24
#Renaming in pop20_wrangled
df_pop24_wrangled2 = df_pop24_wrangled.rename(columns = {
    'STNAME': 'State',
    'CTYNAME': 'County',
    'POPESTIMATE2020': 'Pop2020',
    'POPESTIMATE2021': 'Pop2021',
    'POPESTIMATE2022': 'Pop2022',
    'POPESTIMATE2023': 'Pop2023',
    'POPESTIMATE2024': 'Pop2024',
})

In [112]:
df_pop24_wrangled2

        State             County  Pop2020  Pop2021  Pop2022  Pop2023  Pop2024
0     Alabama            Alabama  5033094  5049196  5076181  5117673  5157699
1     Alabama     Autauga County    58909    59191    59736    60436    61464
2     Alabama     Baldwin County   233244   239411   246577   254107   261608
3     Alabama     Barbour County    24975    24517    24722    24644    24358
4     Alabama        Bibb County    22176    22344    21983    21890    22258
...       ...                ...      ...      ...      ...      ...      ...
3190  Wyoming  Sweetwater County    42196    41630    41322    41288    41273
3191  Wyoming       Teton County    23384    23613    23341    23368    23272
3192  Wyoming       Uinta County    20461    20690    20722    20724    20621
3193  Wyoming    Washakie County     7663     7727     7728     7736     7662
3194  Wyoming      Weston County     6817     6747     6872     6828     6866

[3195 rows x 7 columns]

5. Merging population

In [115]:
# Merge datasets: Mass shootings and Gun sales data 
pop_merged = pd.merge(df_pop20_wrangled2, df_pop24_wrangled2, on='County', how='outer')

In [117]:
pop_merged

,State_x,County,Pop2015,Pop2016,Pop2017,Pop2018,Pop2019,State_y,Pop2020,Pop2021,Pop2022,Pop2023,Pop2024
0,South Carolina,Abbeville County,24814.0,24688.0,24598.0,24637.0,24584.0,South Carolina,24262.0,24263.0,24407.0,24563.0,24607.0
1,Louisiana,Acadia Parish,62696.0,62830.0,62581.0,62315.0,62207.0,Louisiana,57481.0,57228.0,56812.0,56649.0,56604.0
2,Virginia,Accomack County,32930.0,32903.0,32729.0,32603.0,32325.0,Virginia,33397.0,33422.0,33157.0,33288.0,33411.0
3,Idaho,Ada County,433254.0,444929.0,456994.0,469161.0,481880.0,Idaho,498301.0,513098.0,520788.0,526690.0,535799.0
4,Iowa,Adair County,7142.0,7006.0,7047.0,7028.0,7102.0,Iowa,7489.0,7522.0,7457.0,7399.0,7431.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14583,Colorado,Yuma County,10044.0,10057.0,9976.0,9964.0,10020.0,Arizona,205665.0,207743.0,209538.0,215448.0,220310.0
14584,Colorado,Yuma County,10044.0,10057.0,9976.0,9964.0,10020.0,Colorado,9970.0,9926.0,9970.0,9981.0,10048.0
14585,Texas,Zapata County,14474.0,14420.0,14251.0,14151.0,14221.0,Texas,13875.0,13887.0,13841.0,13782.0,13819.0
14586,Texas,Zavala County,12322.0,12125.0,11946.0,11934.0,11807.0,Texas,9660.0,9472.0,9382.0,9339.0,9209.0
14587,South Dakota,Ziebach County,2838.0,2870.0,2747.0,2759.0,2801.0,South Dakota,2393.0,2383.0,2369.0,2322.0,2418.0

6. Consistency checks

In [122]:
#Null values
pop_merged.isnull().sum()

State_x    9
County     0
Pop2015    9
Pop2016    9
Pop2017    9
Pop2018    9
Pop2019    9
State_y    5
Pop2020    5
Pop2021    5
Pop2022    5
Pop2023    5
Pop2024    5
dtype: int64

In [124]:
# Count non-null data points per column
count_per_column = pop_merged.count()

print(count_per_column)

State_x    14579
County     14588
Pop2015    14579
Pop2016    14579
Pop2017    14579
Pop2018    14579
Pop2019    14579
State_y    14583
Pop2020    14583
Pop2021    14583
Pop2022    14583
Pop2023    14583
Pop2024    14583
dtype: int64

In [126]:
#Inspecting null values
pop_merged_nulls = pop_merged[pop_merged.isnull().any(axis=1)]

In [138]:
pop_merged_nulls.shape

(14, 13)

In [140]:
pop_merged_nulls

,State_x,County,Pop2015,Pop2016,Pop2017,Pop2018,Pop2019,State_y,Pop2020,Pop2021,Pop2022,Pop2023,Pop2024
1087,NaN,Capitol Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,964088.0,971938.0,975591.0,983326.0,991508.0
4389,NaN,Greater Bridgeport Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,324397.0,326799.0,328131.0,331300.0,335666.0
5001,Connecticut,Hartford County,896563.0,894282.0,893141.0,892767.0,891349.0,NaN,NaN,NaN,NaN,NaN,NaN
8144,Connecticut,Litchfield County,184171.0,182837.0,181719.0,181151.0,180396.0,NaN,NaN,NaN,NaN,NaN,NaN
8289,NaN,Lower Connecticut River Valley Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,173281.0,175456.0,176159.0,176674.0,177540.0
10352,NaN,Naugatuck Valley Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,449055.0,452095.0,453868.0,457609.0,462220.0
10380,Connecticut,New Haven County,860506.0,858159.0,857845.0,856895.0,853818.0,NaN,NaN,NaN,NaN,NaN,NaN
10383,Connecticut,New London County,269818.0,268639.0,267829.0,267089.0,265784.0,NaN,NaN,NaN,NaN,NaN,NaN
10464,NaN,Northeastern Connecticut Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,95231.0,95624.0,96169.0,96834.0,97701.0
10470,NaN,Northwest Hills Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,112199.0,112952.0,113289.0,113538.0,114101.0
12105,NaN,South Central Connecticut Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,564526.0,568961.0,569866.0,572919.0,576718.0
12109,NaN,Southeastern Connecticut Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,278379.0,278855.0,279398.0,280622.0,282602.0
12464,Connecticut,Tolland County,151815.0,151223.0,151136.0,150913.0,150865.0,NaN,NaN,NaN,NaN,NaN,NaN
14336,NaN,Western Connecticut Planning Region,NaN,NaN,NaN,NaN,NaN,Connecticut,618762.0,623927.0,625454.0,630201.0,637013.0

In [144]:
#Dropping values
pop_merged_clean = pop_merged.dropna()

In [146]:
pop_merged_clean.isnull().sum()

State_x    0
County     0
Pop2015    0
Pop2016    0
Pop2017    0
Pop2018    0
Pop2019    0
State_y    0
Pop2020    0
Pop2021    0
Pop2022    0
Pop2023    0
Pop2024    0
dtype: int64

In [156]:
#Checking duplicates
pop_merged_clean[pop_merged_clean.duplicated()]

,State_x,County,Pop2015,Pop2016,Pop2017,Pop2018,Pop2019,State_y,Pop2020,Pop2021,Pop2022,Pop2023,Pop2024
2842,District of Columbia,District of Columbia,677014.0,687576.0,697079.0,704147.0,708253.0,District of Columbia,670917.0,669256.0,676725.0,687324.0,702250.0
2843,District of Columbia,District of Columbia,677014.0,687576.0,697079.0,704147.0,708253.0,District of Columbia,670917.0,669256.0,676725.0,687324.0,702250.0
2844,District of Columbia,District of Columbia,677014.0,687576.0,697079.0,704147.0,708253.0,District of Columbia,670917.0,669256.0,676725.0,687324.0,702250.0

In [158]:
#Dropping duplicates
pop_merged_clean2 = pop_merged_clean.drop_duplicates()

In [152]:
pop_merged_clean2[pop_merged_clean2.duplicated()]

Empty DataFrame
Columns: [State_x, County, Pop2015, Pop2016, Pop2017, Pop2018, Pop2019, State_y, Pop2020, Pop2021, Pop2022, Pop2023, Pop2024]
Index: []

In [154]:
pop_merged_clean2.isnull().sum()

State_x    0
County     0
Pop2015    0
Pop2016    0
Pop2017    0
Pop2018    0
Pop2019    0
State_y    0
Pop2020    0
Pop2021    0
Pop2022    0
Pop2023    0
Pop2024    0
dtype: int64

7. Wrangling and renaming

In [161]:
#Dropping unnecessary/duplicate columns
pop_merged_clean2 = pop_merged_clean2.drop(columns=['State_y'
                ])

In [163]:
#Renaming columns
pop_merged_clean2 = pop_merged_clean2.rename(columns = {
    'State_x': 'State',
    })

In [165]:
pop_merged_clean2

,State,County,Pop2015,Pop2016,Pop2017,Pop2018,Pop2019,Pop2020,Pop2021,Pop2022,Pop2023,Pop2024
0,South Carolina,Abbeville County,24814.0,24688.0,24598.0,24637.0,24584.0,24262.0,24263.0,24407.0,24563.0,24607.0
1,Louisiana,Acadia Parish,62696.0,62830.0,62581.0,62315.0,62207.0,57481.0,57228.0,56812.0,56649.0,56604.0
2,Virginia,Accomack County,32930.0,32903.0,32729.0,32603.0,32325.0,33397.0,33422.0,33157.0,33288.0,33411.0
3,Idaho,Ada County,433254.0,444929.0,456994.0,469161.0,481880.0,498301.0,513098.0,520788.0,526690.0,535799.0
4,Iowa,Adair County,7142.0,7006.0,7047.0,7028.0,7102.0,7489.0,7522.0,7457.0,7399.0,7431.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14583,Colorado,Yuma County,10044.0,10057.0,9976.0,9964.0,10020.0,205665.0,207743.0,209538.0,215448.0,220310.0
14584,Colorado,Yuma County,10044.0,10057.0,9976.0,9964.0,10020.0,9970.0,9926.0,9970.0,9981.0,10048.0
14585,Texas,Zapata County,14474.0,14420.0,14251.0,14151.0,14221.0,13875.0,13887.0,13841.0,13782.0,13819.0
14586,Texas,Zavala County,12322.0,12125.0,11946.0,11934.0,11807.0,9660.0,9472.0,9382.0,9339.0,9209.0
14587,South Dakota,Ziebach County,2838.0,2870.0,2747.0,2759.0,2801.0,2393.0,2383.0,2369.0,2322.0,2418.0

8. Exporting clean and wrangled dataset

In [168]:
pop_merged_clean2.to_csv(os.path.join(path, '02_Data', 'Prepared', 'population2015-2020.csv'))